before_script:
  - ruby -v
  - which ruby
  - gem install --no-document racc rake rubygems-tasks yard test-unit test-unit-notify simplecov

test:2.6:
  image: ruby:2.6
  script:
    rake test

test:2.7:
  image: ruby:2.7
  script:
    rake test

test:3.0:
  image: ruby:3.0
  script:
    rake test

test:3.1:
  image: ruby:3.1
  script:
    rake test

test:3.2:
  image: ruby:3.2
  script:
    rake test
