before_script:
  - ruby -v
  - which ruby
  - gem install --no-document racc rake rubygems-tasks yard test-unit test-unit-notify simplecov steep

test:3.0:
  image: ruby:3.0
  script:
    rake test

test:3.1:
  image: ruby:3.1
  script:
    rake test

test:3.2:
  image: ruby:3.2
  script:
    rake test typecheck

test:3.2:
  image: ruby:3.3
  script:
    rake test typecheck
