version: 1.0.{build}-{branch}

environment:
  matrix:
    - RUBY_VERSION: 23
    - RUBY_VERSION: 24
    - RUBY_VERSION: 25
    - RUBY_VERSION: 26

install:
  - set PATH=C:\Ruby%RUBY_VERSION%\bin;%PATH%
  - gem install --no-document racc rake rubygems-tasks yard test-unit test-unit-notify pretty_backtrace simplecov

build: off

before_test:
  - ruby -v
  - gem -v

test_script:
  - rake test
